/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as MinhaAreaRouteImport } from './routes/minha-area'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin.events.$eventId'
import { Route as AdminEventsEventIdScoresRouteImport } from './routes/admin.events.$eventId.scores'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAreaRoute = MinhaAreaRouteImport.update({
  id: '/minha-area',
  path: '/minha-area',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventIdScoresRoute =
  AdminEventsEventIdScoresRouteImport.update({
    id: '/scores',
    path: '/scores',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/minha-area': typeof MinhaAreaRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/admin/events/$eventId/scores': typeof AdminEventsEventIdScoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/minha-area': typeof MinhaAreaRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/admin/events/$eventId/scores': typeof AdminEventsEventIdScoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/minha-area': typeof MinhaAreaRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/admin/events/$eventId/scores': typeof AdminEventsEventIdScoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/minha-area'
    | '/ranking'
    | '/reset-password'
    | '/admin/access'
    | '/admin/content'
    | '/admin/finance'
    | '/admin/requests'
    | '/events/$eventId'
    | '/admin/'
    | '/admin/events/$eventId'
    | '/admin/events/$eventId/scores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/minha-area'
    | '/ranking'
    | '/reset-password'
    | '/admin/access'
    | '/admin/content'
    | '/admin/finance'
    | '/admin/requests'
    | '/events/$eventId'
    | '/admin'
    | '/admin/events/$eventId'
    | '/admin/events/$eventId/scores'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/minha-area'
    | '/ranking'
    | '/reset-password'
    | '/admin/access'
    | '/admin/content'
    | '/admin/finance'
    | '/admin/requests'
    | '/events/$eventId'
    | '/admin/'
    | '/admin/events/$eventId'
    | '/admin/events/$eventId/scores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MinhaAreaRoute: typeof MinhaAreaRoute
  RankingRoute: typeof RankingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-area': {
      id: '/minha-area'
      path: '/minha-area'
      fullPath: '/minha-area'
      preLoaderRoute: typeof MinhaAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId/scores': {
      id: '/admin/events/$eventId/scores'
      path: '/scores'
      fullPath: '/admin/events/$eventId/scores'
      preLoaderRoute: typeof AdminEventsEventIdScoresRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
  }
}

interface AdminEventsEventIdRouteChildren {
  AdminEventsEventIdScoresRoute: typeof AdminEventsEventIdScoresRoute
}

const AdminEventsEventIdRouteChildren: AdminEventsEventIdRouteChildren = {
  AdminEventsEventIdScoresRoute: AdminEventsEventIdScoresRoute,
}

const AdminEventsEventIdRouteWithChildren =
  AdminEventsEventIdRoute._addFileChildren(AdminEventsEventIdRouteChildren)

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminContentRoute: AdminContentRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsEventIdRoute: AdminEventsEventIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MinhaAreaRoute: MinhaAreaRoute,
  RankingRoute: RankingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EventsEventIdRoute: EventsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
